
create index PARTSUPP_PART_FKIDX on PARTSUPP(PS_PARTKEY),
create index PARTSUPP_SUPPLIER_FKIDX on PARTSUPP(PS_SUPPKEY);


create INDEX CUSTOMER_NATION_FKIDX on CUSTOMER(C_NATIONKEY);

 
create INDEX SUPPLIER_NATION_FKIDX on SUPPLIER(S_NATIONKEY);

create INDEX NATION_REGIONKEY_FKIDX on NATION (N_REGIONKEY);

create INDEX LINEITEM_PART_SUPP_FKIDX on LINEITEM (L_PARTKEY,L_SUPPKEY);
create INDEX IDX_LINEITEM_ORDERKEY_FKIDX on LINEITEM(L_ORDERKEY);

create INDEX ORDERS_FK1 on ORDERS (O_CUSTKEY);

ANALYZE;
