
alter table PARTSUPP 
add INDEX PARTSUPP_PART_FKIDX (`PS_PARTKEY`),
add INDEX PARTSUPP_SUPPLIER_FKIDX (`PS_SUPPKEY`);

alter table CUSTOMER
add INDEX CUSTOMER_NATION_FKIDX (`C_NATIONKEY`);

alter table SUPPLIER 
add INDEX SUPPLIER_NATION_FKIDX (`S_NATIONKEY`);

alter table NATION
add INDEX NATION_REGIONKEY_FKIDX (`N_REGIONKEY`);

alter table LINEITEM
add INDEX LINEITEM_PART_SUPP_FKIDX (`L_PARTKEY`,`L_SUPPKEY`),
add INDEX IDX_LINEITEM_ORDERKEY_FKIDX (`L_ORDERKEY`);

alter table ORDERS
add INDEX `ORDERS_FK1` (`O_CUSTKEY`);


